# Generated by Django 4.1.5 on 2023-02-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='active',
        ),
        migrations.AddField(
            model_name='products',
            name='avail',
            field=models.BooleanField(default=False),
        ),
    ]
