# Generated by Django 4.1.5 on 2023-02-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_desc_alter_products_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='summary',
            field=models.TextField(default='summary...', max_length=40),
        ),
    ]
